# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from n3ctrl/ControllerDebug.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ControllerDebug(genpy.Message):
  _md5sum = "2879e490b09bd2d41232bc7fbaf6a3c1"
  _type = "n3ctrl/ControllerDebug"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Vector3 des_p
geometry_msgs/Vector3 u_p_p
geometry_msgs/Vector3 u_p_i
geometry_msgs/Vector3 u_p
geometry_msgs/Vector3 des_v
geometry_msgs/Vector3 u_v_p
geometry_msgs/Vector3 u_v_i
geometry_msgs/Vector3 u_v
geometry_msgs/Vector3 k_p_p
geometry_msgs/Vector3 k_p_i
geometry_msgs/Vector3 k_v_p
geometry_msgs/Vector3 k_v_i

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','des_p','u_p_p','u_p_i','u_p','des_v','u_v_p','u_v_i','u_v','k_p_p','k_p_i','k_v_p','k_v_i']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,des_p,u_p_p,u_p_i,u_p,des_v,u_v_p,u_v_i,u_v,k_p_p,k_p_i,k_v_p,k_v_i

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerDebug, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.des_p is None:
        self.des_p = geometry_msgs.msg.Vector3()
      if self.u_p_p is None:
        self.u_p_p = geometry_msgs.msg.Vector3()
      if self.u_p_i is None:
        self.u_p_i = geometry_msgs.msg.Vector3()
      if self.u_p is None:
        self.u_p = geometry_msgs.msg.Vector3()
      if self.des_v is None:
        self.des_v = geometry_msgs.msg.Vector3()
      if self.u_v_p is None:
        self.u_v_p = geometry_msgs.msg.Vector3()
      if self.u_v_i is None:
        self.u_v_i = geometry_msgs.msg.Vector3()
      if self.u_v is None:
        self.u_v = geometry_msgs.msg.Vector3()
      if self.k_p_p is None:
        self.k_p_p = geometry_msgs.msg.Vector3()
      if self.k_p_i is None:
        self.k_p_i = geometry_msgs.msg.Vector3()
      if self.k_v_p is None:
        self.k_v_p = geometry_msgs.msg.Vector3()
      if self.k_v_i is None:
        self.k_v_i = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.des_p = geometry_msgs.msg.Vector3()
      self.u_p_p = geometry_msgs.msg.Vector3()
      self.u_p_i = geometry_msgs.msg.Vector3()
      self.u_p = geometry_msgs.msg.Vector3()
      self.des_v = geometry_msgs.msg.Vector3()
      self.u_v_p = geometry_msgs.msg.Vector3()
      self.u_v_i = geometry_msgs.msg.Vector3()
      self.u_v = geometry_msgs.msg.Vector3()
      self.k_p_p = geometry_msgs.msg.Vector3()
      self.k_p_i = geometry_msgs.msg.Vector3()
      self.k_v_p = geometry_msgs.msg.Vector3()
      self.k_v_i = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_36d().pack(_x.des_p.x, _x.des_p.y, _x.des_p.z, _x.u_p_p.x, _x.u_p_p.y, _x.u_p_p.z, _x.u_p_i.x, _x.u_p_i.y, _x.u_p_i.z, _x.u_p.x, _x.u_p.y, _x.u_p.z, _x.des_v.x, _x.des_v.y, _x.des_v.z, _x.u_v_p.x, _x.u_v_p.y, _x.u_v_p.z, _x.u_v_i.x, _x.u_v_i.y, _x.u_v_i.z, _x.u_v.x, _x.u_v.y, _x.u_v.z, _x.k_p_p.x, _x.k_p_p.y, _x.k_p_p.z, _x.k_p_i.x, _x.k_p_i.y, _x.k_p_i.z, _x.k_v_p.x, _x.k_v_p.y, _x.k_v_p.z, _x.k_v_i.x, _x.k_v_i.y, _x.k_v_i.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.des_p is None:
        self.des_p = geometry_msgs.msg.Vector3()
      if self.u_p_p is None:
        self.u_p_p = geometry_msgs.msg.Vector3()
      if self.u_p_i is None:
        self.u_p_i = geometry_msgs.msg.Vector3()
      if self.u_p is None:
        self.u_p = geometry_msgs.msg.Vector3()
      if self.des_v is None:
        self.des_v = geometry_msgs.msg.Vector3()
      if self.u_v_p is None:
        self.u_v_p = geometry_msgs.msg.Vector3()
      if self.u_v_i is None:
        self.u_v_i = geometry_msgs.msg.Vector3()
      if self.u_v is None:
        self.u_v = geometry_msgs.msg.Vector3()
      if self.k_p_p is None:
        self.k_p_p = geometry_msgs.msg.Vector3()
      if self.k_p_i is None:
        self.k_p_i = geometry_msgs.msg.Vector3()
      if self.k_v_p is None:
        self.k_v_p = geometry_msgs.msg.Vector3()
      if self.k_v_i is None:
        self.k_v_i = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 288
      (_x.des_p.x, _x.des_p.y, _x.des_p.z, _x.u_p_p.x, _x.u_p_p.y, _x.u_p_p.z, _x.u_p_i.x, _x.u_p_i.y, _x.u_p_i.z, _x.u_p.x, _x.u_p.y, _x.u_p.z, _x.des_v.x, _x.des_v.y, _x.des_v.z, _x.u_v_p.x, _x.u_v_p.y, _x.u_v_p.z, _x.u_v_i.x, _x.u_v_i.y, _x.u_v_i.z, _x.u_v.x, _x.u_v.y, _x.u_v.z, _x.k_p_p.x, _x.k_p_p.y, _x.k_p_p.z, _x.k_p_i.x, _x.k_p_i.y, _x.k_p_i.z, _x.k_v_p.x, _x.k_v_p.y, _x.k_v_p.z, _x.k_v_i.x, _x.k_v_i.y, _x.k_v_i.z,) = _get_struct_36d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_36d().pack(_x.des_p.x, _x.des_p.y, _x.des_p.z, _x.u_p_p.x, _x.u_p_p.y, _x.u_p_p.z, _x.u_p_i.x, _x.u_p_i.y, _x.u_p_i.z, _x.u_p.x, _x.u_p.y, _x.u_p.z, _x.des_v.x, _x.des_v.y, _x.des_v.z, _x.u_v_p.x, _x.u_v_p.y, _x.u_v_p.z, _x.u_v_i.x, _x.u_v_i.y, _x.u_v_i.z, _x.u_v.x, _x.u_v.y, _x.u_v.z, _x.k_p_p.x, _x.k_p_p.y, _x.k_p_p.z, _x.k_p_i.x, _x.k_p_i.y, _x.k_p_i.z, _x.k_v_p.x, _x.k_v_p.y, _x.k_v_p.z, _x.k_v_i.x, _x.k_v_i.y, _x.k_v_i.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.des_p is None:
        self.des_p = geometry_msgs.msg.Vector3()
      if self.u_p_p is None:
        self.u_p_p = geometry_msgs.msg.Vector3()
      if self.u_p_i is None:
        self.u_p_i = geometry_msgs.msg.Vector3()
      if self.u_p is None:
        self.u_p = geometry_msgs.msg.Vector3()
      if self.des_v is None:
        self.des_v = geometry_msgs.msg.Vector3()
      if self.u_v_p is None:
        self.u_v_p = geometry_msgs.msg.Vector3()
      if self.u_v_i is None:
        self.u_v_i = geometry_msgs.msg.Vector3()
      if self.u_v is None:
        self.u_v = geometry_msgs.msg.Vector3()
      if self.k_p_p is None:
        self.k_p_p = geometry_msgs.msg.Vector3()
      if self.k_p_i is None:
        self.k_p_i = geometry_msgs.msg.Vector3()
      if self.k_v_p is None:
        self.k_v_p = geometry_msgs.msg.Vector3()
      if self.k_v_i is None:
        self.k_v_i = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 288
      (_x.des_p.x, _x.des_p.y, _x.des_p.z, _x.u_p_p.x, _x.u_p_p.y, _x.u_p_p.z, _x.u_p_i.x, _x.u_p_i.y, _x.u_p_i.z, _x.u_p.x, _x.u_p.y, _x.u_p.z, _x.des_v.x, _x.des_v.y, _x.des_v.z, _x.u_v_p.x, _x.u_v_p.y, _x.u_v_p.z, _x.u_v_i.x, _x.u_v_i.y, _x.u_v_i.z, _x.u_v.x, _x.u_v.y, _x.u_v.z, _x.k_p_p.x, _x.k_p_p.y, _x.k_p_p.z, _x.k_p_i.x, _x.k_p_i.y, _x.k_p_i.z, _x.k_v_p.x, _x.k_v_p.y, _x.k_v_p.z, _x.k_v_i.x, _x.k_v_i.y, _x.k_v_i.z,) = _get_struct_36d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
